version: '3.9'
services:
  web:
    image: nginx
    container_name: impact-meme-generator
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    restart: unless-stopped
